// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2xCjN8f6PUMxFu0OUeR3FpQNIio2BihQ',
    appId: '1:923604832175:web:3ba1cc9c49cd0aaa3be95a',
    messagingSenderId: '923604832175',
    projectId: 'new-proj-92781',
    authDomain: 'new-proj-92781.firebaseapp.com',
    storageBucket: 'new-proj-92781.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcecybxvdnZluojshv4uFkBsM2f9A-zY',
    appId: '1:923604832175:android:23fa3b96b3151d903be95a',
    messagingSenderId: '923604832175',
    projectId: 'new-proj-92781',
    storageBucket: 'new-proj-92781.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgMHk4R_DG1wHfL8hWegR92WftjZ8vF4',
    appId: '1:923604832175:ios:0cba4eda3129ebea3be95a',
    messagingSenderId: '923604832175',
    projectId: 'new-proj-92781',
    storageBucket: 'new-proj-92781.appspot.com',
    iosClientId: '923604832175-mn01t6rag85ptvjq7jl15jkflcj05lvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoa',
  );
}
